debug: false
spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql:3306/aonebakery?useUnicode=true&characterEncoding=utf-8
      username: root
      password: hn3ioeEHU42mxyy4DRQd
    secondary:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://btsa1.tact.com.hk:1433;DatabaseName=mrs
      username: ai
      password: a1ai2022
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
minio:
  extranet: http://minio.a1-bakery.remoc.com.cn:8083/a1-bakery/
  endpoint: http://minio:9000/
  access-key: minio
  secret-key: BLTzN7DpHSkq9EEsd44L